import Head from "next/head";
import { LandingPage } from "@components/landing/LandingPage";
import { LayoutComponent } from "@components/layout/LayoutComponent";
import Toaster from "@components/Toaster";
import RecordingPage from "./create";

export default function Home() {
  const IS_APP_ACTIVE = true;

  return (
    <>
      <Head>
        <title>øhr</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LayoutComponent
        showWallet={IS_APP_ACTIVE && "none"}
        showLogo={IS_APP_ACTIVE && true}
        showTitle="Record"
      >
        <Toaster />
        {/* <LandingPage isAppActive={IS_APP_ACTIVE} /> */}
        <RecordingPage />
      </LayoutComponent>
    </>
  );
}
